# Generated by Django 3.2 on 2022-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('dest', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('ms', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
