# Generated by Django 3.2 on 2022-07-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0002_auto_20220708_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripmodel',
            old_name='rno',
            new_name='srno',
        ),
    ]
