# Generated by Django 3.2 on 2022-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0004_auto_20220711_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmodel',
            name='srno',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
